name: ci-every push-test

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  ci-every_push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Go back to Project Repository
        uses: actions/checkout@v3
        with:
          repository: Karthik-md/madeWS2024
          path: project

      - name: List files in project directory
        run: |
          ls -la project

      - name: Find and Set Permissions for Requirements Files
        run: |
          find . -name "requirements.txt" -exec chmod +r {} \;

      - name: Install Dependencies from All Requirements Files
        run: |
          find . -name "requirements.txt" -exec pip install -r {} \;

      - name: Set execute permissions for test.sh scripts
        run: |
          find . -name "test.sh" -exec chmod +x {} \;

      - name: Find and Run Test Scripts
        run: |
          find . -name "test.sh" -execdir bash -c './test.sh' \;
